### ISSUE TITLE
Add a command to describe a SiteWhere Instance

### ISSUE THREAD

**Issue by jorgevillaverde-sitewhere** [sitewhere/swctl#29]
Currently, `swctl instances` takes no arguments and prints the list of installed SiteWhere Instances, e.i.

```
NAME            NAMESPACE       CONFIG TMPL     DATESET TMPL    TM STATUS       UM STATUS
sitewhere       sitewhere       default         default                                  
```

We need to modify that command to allow to take as argument the name of the instance to describe. So if no argument is provided, the command remains the same, but if an instance name is provided we need to provide a more detailed information of the instance. 

This is an example of `SiteWhereInstance` CRD, that we need display to the user. We may need a way to reduce the amount of information to the user. @derekadams what are your thought on this?   

```
  configuration:
    infrastructure:
      grpc:
        backoffMultiplier: 1.5
        initialBackoffSeconds: 10
        maxBackoffSeconds: 600
        maxRetryCount: 6
        resolveFQDN: false
      kafka:
        defaultTopicPartitions: 8
        defaultTopicReplicationFactor: 3
        hostname: sitewhere-kafka-kafka-bootstrap
        port: 9092
      metrics:
        enabled: true
        httpPort: 9090
      namespace: sitewhere-system
      redis:
        hostname: sitewhere-redis-headless.sitewhere-system
        port: 6379
    persistenceConfigurations:
      rdbConfigurations:
        postgres:
          configuration:
            hostname: sitewhere-db-postgresql.sitewhere-system
            maxConnections: 5
            password: sitewhere
            port: 5432
            username: sitewhere
          type: postgres95
      timeSeriesConfigurations:
        influxdb:
          configuration:
            databaseName: tenant_${tenant.id}
            hostname: sitewhere-influxdb.sitewhere-system
            port: 8086
          type: influxdb
  configurationTemplate: default
  datasetTemplate: default
  dockerSpec:
    registry: docker.io
    repository: sitewhere
    tag: "3.0"
```

Also, each instance has a set of microservices that we can list.

**Comment by derekadams** [comment]
Maybe we can have the output be one section per top-level element in the output above, then the list of microservices and their corresponding deployments. So something like:

**Configuration Template**: default
**Dataset Template**: default
**Infrastructure Configuration Settings:**
```
      grpc:
        backoffMultiplier: 1.5
        initialBackoffSeconds: 10
        maxBackoffSeconds: 600
        maxRetryCount: 6
        resolveFQDN: false
      kafka:
        defaultTopicPartitions: 8
        defaultTopicReplicationFactor: 3
        hostname: sitewhere-kafka-kafka-bootstrap
        port: 9092
      metrics:
        enabled: true
        httpPort: 9090
      namespace: sitewhere-system
      redis:
        hostname: sitewhere-redis-headless.sitewhere-system
        port: 6379
```
**Persistence Configurations**
```
      rdbConfigurations:
        postgres:
          configuration:
            hostname: sitewhere-db-postgresql.sitewhere-system
            maxConnections: 5
            password: sitewhere
            port: 5432
            username: sitewhere
          type: postgres95
      timeSeriesConfigurations:
        influxdb:
          configuration:
            databaseName: tenant_${tenant.id}
            hostname: sitewhere-influxdb.sitewhere-system
            port: 8086
          type: influxdb
```
**Default Docker Specification**
```
    registry: docker.io
    repository: sitewhere
    tag: "3.0"
```

**Microservices**
| Microservice | Deployment |
|:--------------|:--------------|
| Asset Management | default-asset-management-12673561263 |
| Batch Operations    | default-batch-operations-2394872374837 |
...
```
